FROM openjdk:8
EXPOSE 8080
ADD target/devops-integration.jar devops-integration.jar
ENTRYPOINT ["java" , "-jar","/devops-integration.jar"]

# This is a comment in a Dockerfiles
# This is a comment in a Dockerfiles
#Push successful D:\: Pushed 1 commit to origin/facture
# This is a comment in a Dockerfiles
# This is a comment in a Dockerfiles
#jbj
